name: dependency-jobs
run-name: ${{ github.actor }} is dependency-jobs-workflow CI

on: [push]

jobs:
  checkout-job:  ### job1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: echo "checking out"

      - name:  Listing contents 
        run: |
          pwd
          ls

  install-packages-job:  ### job2
    runs-on: ubuntu-latest     
    needs: ["checkout-job"]

    steps:
      - name: Install packages
        run: echo "installing packages"

      - name: check jobs
        shell: bash
        run: echo "job2 success"

  run-test-job:  ### job3
    runs-on: ubuntu-latest 
    needs: ["install-packages-job"] 

    steps:
      - name: Run-test
        run: echo "job3 running test"

